language: csharp
solution: TimeTracking.sln
install:
  - nuget restore TimeTracking.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TimeTracking.sln
  # - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TimeTracking.Tests/bin/Release/TimeTracking.Tests.dll
